# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'Berkeley Psychology Graduate Blog'
description: 'Berkeley Psychology Graduate Blog'
permalink: pretty
logo: "https://upload.wikimedia.org/wikipedia/commons/7/74/Greek_uc_psi.svg"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Blog
  url: /blog/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "Berkeley Psychology Graduate Student Spotlights"
    feature_text: |
      Berkeley Psychology Graduate Student Spotlights
    feature_image: "https://picsum.photos/2560/600?image=866"
